### ISSUE TITLE
Compilation errors/warnings with WIO Terminal

### ISSUE THREAD

**Issue by dennisma** [Seeed-Studio/Seeed_Arduino_Linechart#1]
It appears this library uses the deduced return type feature of C++14.  However the Seeedstudio WIO Terminal compiles at C++11  (-std=gnu++11) (see the platform.txt for the Arduino IDE compilation).   

You might want to either change the cpp compilation for options in the platform.txt to -std=gnu++14 OR don't use deduced return types.

**Comment by LynnL4** [comment]
thanks, we'll try C + + 14, but we need some compatibility tests.
