### ISSUE TITLE
Crashing when drawing Temp Chart

### ISSUE THREAD

**Issue by MoosHam** [Seeed-Studio/Seeed_Arduino_Linechart#7]
My Code for WioTerminal occasionally starts to crash when using this lib.

Use Case: I wrote a program that is receiving MQTT data with the hourly temperature outside in °C for the last 26 hours.
it worked for a while, but then it started crashing (freezing the WioTerminal). 

It most recently happend with below data:

[{"hour":"14","mean":2},{"hour":"15","mean":1.6},{"hour":"16","mean":0.9},{"hour":"17","mean":-0.2},{"hour":"18","mean":-0.4},{"hour":"19","mean":-0.3},{"hour":"20","mean":-0.3},{"hour":"21","mean":-0.2},{"hour":"22","mean":0},{"hour":"23","mean":0.1},{"hour":"00","mean":0},{"hour":"01","mean":0.2},{"hour":"02","mean":0.2},{"hour":"03","mean":0},{"hour":"04","mean":-0.2},{"hour":"05","mean":-0.1},{"hour":"06","mean":0},{"hour":"07","mean":0.2},{"hour":"08","mean":0.6},{"hour":"09","mean":1},{"hour":"10","mean":1.7},{"hour":"11","mean":2.1},{"hour":"12","mean":2.8},{"hour":"13","mean":2.7},{"hour":"14","mean":2.1},{"hour":"15","mean":1.6}]

I load one row that is only "0" plus the "mean" value from above data into a data variable:
doubles data[2];

when I call content.draw(); with above example, the WioTerminal stops working. I have to power cycle it.

I tried to negate the numbers in above sample by multiplying with -1, then it works.

Any idea what this can be?
I would also be happy if the lb would fail more gracefully, for example diplaying an error instead of just crashing.

thansk
MoosHam

**Comment by jmiller3931** [comment]
I'm seeing something similar. It pretty much makes it unusable for me. I have not done an analysis to determine any pattern but anecdotally, it locks up more on slow-changing data than it does on static or fast-changing data.  Besides, it looks like MoosHam provided a test case, above.

**Comment by Pillar1989** [comment]
Please&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Seeed-Studio/Seeed_Arduino_Linechart"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月3日(星期六) 凌晨3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Seeed-Studio/Seeed_Arduino_Linechart] Crashing when drawing Temp Chart (#7)





 
I'm seeing something similar. It pretty much makes it unusable for me. I have not done an analysis to determine any pattern but anecdotally, it locks up more on slow-changing data than it does on static or fast-changing data.  Besides, it looks like MoosHam provided a test case, above.

**Comment by LynnL4** [comment]
hi
refer https://github.com/Seeed-Studio/Seeed_Arduino_Linechart/issues/9
