### ISSUE TITLE
compiling for wio_terminal has compile errors 

### ISSUE THREAD

**Issue by neilh10** [Seeed-Studio/Seeed_Arduino_Linechart#8]
When compiling supplied example basic.ino for wio_terminal with Platformio SAMD51 has errors.

In file included from lib\Seeed_Arduino_Linechart/seeed_line_chart.h:2:0,
                 from D:/usr/a/PlatformIO/Projects/wioT_linechart/src/basic.ino:1:
lib\Seeed_Arduino_Linechart/seeed_graphics_base.h: At global scope:
lib\Seeed_Arduino_Linechart/seeed_graphics_base.h:25:23: error: 'value' function uses 'auto' type specifier without trailing return type
 auto & name(type value) {                                 \
                       ^
lib\Seeed_Arduino_Linechart/seeed_graphics_base.h:121:9: note: in expansion of macro 'xvprop'
         xvprop(point,   value, (return_type *));
         ^~~~~~
lib\Seeed_Arduino_Linechart/seeed_graphics_base.h:25:23: note: deduced return type only available with -std=c++14 or -std=gnu++14
 auto & name(type value) {                                 \
                       ^
lib\Seeed_Arduino_Linechart/seeed_graphics_base.h:121:9: note: in expansion of macro 'xvprop'
         xvprop(point,   value, (return_type *));

**To Reproduce**
Very reproducible, and many other errors. 

Processing seeed_wio_terminal (platform: atmelsam; board: seeed_wio_terminal; framework: arduino)
----------------------------------------------------------------------------------------------------------------------------------------------
CONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/seeed_wio_terminal.html
PLATFORM: Atmel SAM (6.3.1) > Seeeduino Wio Terminal
HARDWARE: SAMD51P19A 120MHz, 192KB RAM, 496KB Flash
DEBUG: Current (atmel-ice) External (atmel-ice, blackmagic, jlink)
PACKAGES:
 - framework-arduino-samd-seeed 1.8.1
 - framework-cmsis 2.50400.181126 (5.4.0)
 - framework-cmsis-atmel 1.2.2
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
Converting basic.ino
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ deep+, Compatibility ~ soft
Found 17 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Seeed_Arduino_LCD> 1.6.0+sha.6bc2cc1
|   |-- <SPI> 1.0
|   |   |-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e    
|   |-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e        
|-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e
|-- <Seeed Arduino Linechart> 1.0.0
|   |-- <Seeed_Arduino_LCD> 1.6.0+sha.6bc2cc1
|   |   |-- <SPI> 1.0
|   |   |   |-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e
|   |   |-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e    
|   |-- <SPI> 1.0
|   |   |-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e    
|   |-- <Adafruit Zero DMA Library> 1.1.0+sha.655916e        
Building in release mode
Compiling .pio\build\seeed_wio_terminal\src\basic.ino.cpp.o

                       ~~~~~~~~^~~~~

**Expected behavior**
Expect it to compile with no errors when using supplied example Basic.ino
A clear and concise description of what you expected to happen.


**Desktop (please complete the following information):**
Windows 10

**Comment by RocketManRC** [comment]
I discovered the solution here which for some reason is not easy to find: https://forum.seeedstudio.com/t/linechart-library-for-wio-terminal-on-platformio-ide-needs-build-flags-std-gnu-14/258456. 

Add the following lines to PlatformIO.ini:

build_unflags = -std=gnu++11
build_flags = -std=gnu++14

**Comment by neilh10** [comment]
Hey thanks.

**Comment by neilh10** [comment]
works for me
